-- ============================================================================
-- DB-018: OFFLINE SYNC QUEUE & CONFLICT TABLES
-- File: offline_sync.sql
--
-- SRS:
--   DB-018  Offline sync queue & conflict tables
--   OFF-04  Durable, ordered, resumable, idempotent sync queue
--   OFF-05  Version-based conflict detection; critical records are not
--           silently overwritten and both versions remain available
--
-- Scope:
--   - PostgreSQL server-side offline synchronization state
--   - Durable ordered sync queue
--   - Idempotency keys and retry state
--   - Version ledger for syncable records
--   - Conflict capture preserving client + server versions
--   - Human-resolution workflow
--   - Tenant isolation / RLS
--   - Mobile SQLite + Android Keystore / iOS Keychain guidance
--
-- IMPORTANT:
--   DB-018 is an incremental schema module. Existing schema files 01-18 are
--   not modified by this file.
--
--   The mobile SQLite database is NOT created in PostgreSQL. This file provides
--   the server-side contract and implementation guidance for the mobile team.
-- ============================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS offline_sync;


-- ============================================================================
-- 1. SYNCABLE RECORD VERSION LEDGER
-- ============================================================================
-- PostgreSQL cannot enforce a "version column exists" rule across arbitrary
-- application tables. This ledger provides one authoritative server-side
-- version for every registered syncable record until each domain table is
-- explicitly migrated to carry its own NOT NULL version BIGINT column.
--
-- Domain teams should treat version as an optimistic-concurrency token:
--   client base_version = server current_version -> update permitted
--   client base_version <> server current_version -> conflict
-- ============================================================================

CREATE TABLE offline_sync.syncable_record_versions
(
    organization_id UUID NOT NULL,
    record_type TEXT NOT NULL,
    record_id UUID NOT NULL,

    version BIGINT NOT NULL DEFAULT 1,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_syncable_record_versions
        PRIMARY KEY (organization_id, record_type, record_id),

    CONSTRAINT fk_syncable_record_versions_organization
        FOREIGN KEY (organization_id)
        REFERENCES tenant_and_configuration.tenants(id),

    CONSTRAINT chk_syncable_record_versions_record_type
        CHECK (length(trim(record_type)) > 0),

    CONSTRAINT chk_syncable_record_versions_version
        CHECK (version >= 1)
);

CREATE INDEX idx_syncable_record_versions_org_type
    ON offline_sync.syncable_record_versions
    (organization_id, record_type);

CREATE INDEX idx_syncable_record_versions_record
    ON offline_sync.syncable_record_versions
    (record_type, record_id);


-- ============================================================================
-- 2. DURABLE OFFLINE SYNC QUEUE
-- ============================================================================
-- One queue row represents one client operation.
--
-- Idempotency:
--   idempotency_key must be stable across retries of the same client
--   operation. The unique constraint prevents duplicate enqueueing.
--
-- Ordering:
--   sequence_no is allocated per organization + device.
--
-- Resumability:
--   A queue row is retained until terminal completion or explicit conflict.
--   Disconnects/retries therefore do not lose the operation.
-- ============================================================================

CREATE TABLE offline_sync.sync_queue
(
    id UUID NOT NULL DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,
    device_id UUID NOT NULL,

    sequence_no BIGINT NOT NULL,

    record_type TEXT NOT NULL,
    record_id UUID NOT NULL,

    operation TEXT NOT NULL,

    -- Client's version of the record before applying this operation.
    base_version BIGINT NOT NULL,

    -- Complete operation payload supplied by the client.
    payload JSONB NOT NULL,

    -- Stable UUID/token generated by the client for retry-safe submission.
    idempotency_key UUID NOT NULL,

    status TEXT NOT NULL DEFAULT 'pending',

    attempt_count INTEGER NOT NULL DEFAULT 0,

    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    locked_at TIMESTAMPTZ NULL,
    locked_by TEXT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,

    last_error TEXT NULL,

    CONSTRAINT pk_sync_queue
        PRIMARY KEY (id),

    CONSTRAINT fk_sync_queue_organization
        FOREIGN KEY (organization_id)
        REFERENCES tenant_and_configuration.tenants(id),

    CONSTRAINT fk_sync_queue_device
        FOREIGN KEY (device_id)
        REFERENCES identity_authentication_sessions.devices(id),

    CONSTRAINT uq_sync_queue_org_idempotency
        UNIQUE (organization_id, idempotency_key),

    CONSTRAINT uq_sync_queue_org_device_sequence
        UNIQUE (organization_id, device_id, sequence_no),

    CONSTRAINT chk_sync_queue_sequence
        CHECK (sequence_no >= 1),

    CONSTRAINT chk_sync_queue_record_type
        CHECK (length(trim(record_type)) > 0),

    CONSTRAINT chk_sync_queue_operation
        CHECK (
            operation IN (
                'create',
                'update',
                'delete'
            )
        ),

    CONSTRAINT chk_sync_queue_base_version
        CHECK (base_version >= 0),

    CONSTRAINT chk_sync_queue_attempt_count
        CHECK (attempt_count >= 0),

    CONSTRAINT chk_sync_queue_status
        CHECK (
            status IN (
                'pending',
                'processing',
                'completed',
                'failed',
                'conflict'
            )
        ),

    CONSTRAINT chk_sync_queue_completed_timestamp
        CHECK (
            status <> 'completed'
            OR completed_at IS NOT NULL
        ),

    CONSTRAINT chk_sync_queue_conflict_status
        CHECK (
            status <> 'conflict'
            OR completed_at IS NULL
        )
);

CREATE INDEX idx_sync_queue_dispatch
    ON offline_sync.sync_queue
    (
        organization_id,
        device_id,
        status,
        available_at,
        sequence_no
    )
    WHERE status IN ('pending', 'processing', 'failed');

CREATE INDEX idx_sync_queue_record
    ON offline_sync.sync_queue
    (
        organization_id,
        record_type,
        record_id,
        sequence_no
    );

CREATE INDEX idx_sync_queue_idempotency
    ON offline_sync.sync_queue
    (
        organization_id,
        idempotency_key
    );


-- ============================================================================
-- 3. CONFLICT TABLE
-- ============================================================================
-- OFF-05:
--   Never silently overwrite a conflicting critical record.
--
-- Both representations are retained:
--   - client_version + client_payload
--   - server_version + server_payload
--
-- Resolution is an explicit human action.
-- ============================================================================

CREATE TABLE offline_sync.sync_conflicts
(
    id UUID NOT NULL DEFAULT gen_random_uuid(),

    organization_id UUID NOT NULL,

    sync_queue_id UUID NOT NULL,

    record_type TEXT NOT NULL,
    record_id UUID NOT NULL,

    client_version BIGINT NOT NULL,
    server_version BIGINT NOT NULL,

    client_payload JSONB NOT NULL,
    server_payload JSONB NOT NULL,

    detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    detected_by_device_id UUID NULL,

    status TEXT NOT NULL DEFAULT 'open',

    resolution TEXT NULL,
    resolution_payload JSONB NULL,
    resolution_notes TEXT NULL,

    resolved_at TIMESTAMPTZ NULL,
    resolved_by UUID NULL,

    CONSTRAINT pk_sync_conflicts
        PRIMARY KEY (id),

    CONSTRAINT fk_sync_conflicts_organization
        FOREIGN KEY (organization_id)
        REFERENCES tenant_and_configuration.tenants(id),

    CONSTRAINT fk_sync_conflicts_sync_queue
        FOREIGN KEY (sync_queue_id)
        REFERENCES offline_sync.sync_queue(id),

    CONSTRAINT fk_sync_conflicts_device
        FOREIGN KEY (detected_by_device_id)
        REFERENCES identity_authentication_sessions.devices(id),

    CONSTRAINT fk_sync_conflicts_resolved_by
        FOREIGN KEY (resolved_by)
        REFERENCES identity_authentication_sessions.users(id),

    CONSTRAINT chk_sync_conflicts_record_type
        CHECK (length(trim(record_type)) > 0),

    CONSTRAINT chk_sync_conflicts_client_version
        CHECK (client_version >= 0),

    CONSTRAINT chk_sync_conflicts_server_version
        CHECK (server_version >= 1),

    CONSTRAINT chk_sync_conflicts_versions_differ
        CHECK (client_version <> server_version),

    CONSTRAINT chk_sync_conflicts_status
        CHECK (
            status IN (
                'open',
                'in_review',
                'resolved',
                'rejected'
            )
        ),

    CONSTRAINT chk_sync_conflicts_resolution
        CHECK (
            status IN ('open', 'in_review')
            OR (
                resolution IS NOT NULL
                AND resolved_at IS NOT NULL
                AND resolved_by IS NOT NULL
            )
        ),

    CONSTRAINT chk_sync_conflicts_resolution_type
        CHECK (
            resolution IS NULL
            OR resolution IN (
                'accept_client',
                'keep_server',
                'merge'
            )
        )
);

CREATE INDEX idx_sync_conflicts_open
    ON offline_sync.sync_conflicts
    (
        organization_id,
        status,
        detected_at
    )
    WHERE status IN ('open', 'in_review');

CREATE INDEX idx_sync_conflicts_record
    ON offline_sync.sync_conflicts
    (
        organization_id,
        record_type,
        record_id,
        detected_at
    );

CREATE INDEX uq_sync_conflicts_active_record
    ON offline_sync.sync_conflicts
    (
        organization_id,
        record_type,
        record_id
    )
    WHERE status IN ('open', 'in_review');


-- ============================================================================
-- 4. SERVER VERSION ADVANCEMENT
-- ============================================================================
-- Advances a syncable record from an expected version to the next version.
-- This is the optimistic-concurrency gate.
--
-- If expected_version does not match, no update is performed and FALSE is
-- returned. The caller must create a conflict using the client payload and
-- the current server representation.
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.advance_record_version
(
    p_organization_id UUID,
    p_record_type TEXT,
    p_record_id UUID,
    p_expected_version BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_new_version BIGINT;
BEGIN
    IF p_organization_id IS NULL
       OR p_record_type IS NULL
       OR length(trim(p_record_type)) = 0
       OR p_record_id IS NULL
       OR p_expected_version < 0
    THEN
        RAISE EXCEPTION 'Invalid sync version arguments';
    END IF;

    UPDATE offline_sync.syncable_record_versions
       SET version = version + 1,
           updated_at = CURRENT_TIMESTAMP
     WHERE organization_id = p_organization_id
       AND record_type = p_record_type
       AND record_id = p_record_id
       AND version = p_expected_version
    RETURNING version
         INTO v_new_version;

    IF v_new_version IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN v_new_version;
END;
$$;


-- ============================================================================
-- 5. REGISTER / INITIALIZE A SYNCABLE RECORD
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.register_syncable_record
(
    p_organization_id UUID,
    p_record_type TEXT,
    p_record_id UUID,
    p_initial_version BIGINT DEFAULT 1
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_version BIGINT;
BEGIN
    IF p_organization_id IS NULL
       OR p_record_type IS NULL
       OR length(trim(p_record_type)) = 0
       OR p_record_id IS NULL
       OR p_initial_version < 1
    THEN
        RAISE EXCEPTION 'Invalid syncable record registration arguments';
    END IF;

    INSERT INTO offline_sync.syncable_record_versions
    (
        organization_id,
        record_type,
        record_id,
        version
    )
    VALUES
    (
        p_organization_id,
        p_record_type,
        p_record_id,
        p_initial_version
    )
    ON CONFLICT
    (
        organization_id,
        record_type,
        record_id
    )
    DO NOTHING
    RETURNING version
    INTO v_version;

    IF v_version IS NOT NULL THEN
        RETURN v_version;
    END IF;

    SELECT version
      INTO v_version
      FROM offline_sync.syncable_record_versions
     WHERE organization_id = p_organization_id
       AND record_type = p_record_type
       AND record_id = p_record_id;

    RETURN v_version;
END;
$$;


-- ============================================================================
-- 6. IDEMPOTENT QUEUE INSERT
-- ============================================================================
-- Retrying the same idempotency key returns the existing queue row instead of
-- inserting a duplicate operation.
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.enqueue
(
    p_organization_id UUID,
    p_device_id UUID,
    p_sequence_no BIGINT,
    p_record_type TEXT,
    p_record_id UUID,
    p_operation TEXT,
    p_base_version BIGINT,
    p_payload JSONB,
    p_idempotency_key UUID
)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
    v_id UUID;
BEGIN
    IF p_organization_id IS NULL
       OR p_device_id IS NULL
       OR p_sequence_no < 1
       OR p_record_type IS NULL
       OR length(trim(p_record_type)) = 0
       OR p_record_id IS NULL
       OR p_operation NOT IN ('create', 'update', 'delete')
       OR p_base_version < 0
       OR p_payload IS NULL
       OR p_idempotency_key IS NULL
    THEN
        RAISE EXCEPTION 'Invalid sync queue arguments';
    END IF;

    INSERT INTO offline_sync.sync_queue
    (
        organization_id,
        device_id,
        sequence_no,
        record_type,
        record_id,
        operation,
        base_version,
        payload,
        idempotency_key
    )
    VALUES
    (
        p_organization_id,
        p_device_id,
        p_sequence_no,
        p_record_type,
        p_record_id,
        p_operation,
        p_base_version,
        p_payload,
        p_idempotency_key
    )
    ON CONFLICT
    (
        organization_id,
        idempotency_key
    )
    DO NOTHING
    RETURNING id
    INTO v_id;

    IF v_id IS NOT NULL THEN
        RETURN v_id;
    END IF;

    SELECT id
      INTO v_id
      FROM offline_sync.sync_queue
     WHERE organization_id = p_organization_id
       AND idempotency_key = p_idempotency_key;

    RETURN v_id;
END;
$$;


-- ============================================================================
-- 7. WORKER-SAFE QUEUE CLAIMING
-- ============================================================================
-- Claims exactly one eligible operation for the current authenticated tenant.
--
-- Concurrency:
--   FOR UPDATE SKIP LOCKED prevents two workers from claiming the same row.
--
-- Ordering:
--   A row is eligible only when no lower sequence number for the same device
--   remains non-terminal. This prevents later operations from overtaking an
--   earlier operation after reconnect/retry.
--
-- Security:
--   Tenant context comes from app.organization_id. The organization is NOT
--   accepted as an authorization parameter.
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.claim_next
(
    p_worker_id TEXT,
    p_device_id UUID DEFAULT NULL
)
RETURNS offline_sync.sync_queue
LANGUAGE plpgsql
AS $$
DECLARE
    v_organization_id UUID;
    v_claimed offline_sync.sync_queue%ROWTYPE;
BEGIN
    v_organization_id := app.require_organization_context();

    IF p_worker_id IS NULL OR length(trim(p_worker_id)) = 0 THEN
        RAISE EXCEPTION 'Worker identifier is required';
    END IF;

    WITH candidate AS
    (
        SELECT q.id
          FROM offline_sync.sync_queue q
         WHERE q.organization_id = v_organization_id
           AND q.status IN ('pending', 'failed')
           AND q.available_at <= CURRENT_TIMESTAMP
           AND (
               p_device_id IS NULL
               OR q.device_id = p_device_id
           )
           AND NOT EXISTS
           (
               SELECT 1
                 FROM offline_sync.sync_queue earlier
                WHERE earlier.organization_id = q.organization_id
                  AND earlier.device_id = q.device_id
                  AND earlier.sequence_no < q.sequence_no
                  AND earlier.status <> 'completed'
           )
         ORDER BY q.device_id, q.sequence_no, q.available_at, q.created_at
         FOR UPDATE SKIP LOCKED
         LIMIT 1
    )
    UPDATE offline_sync.sync_queue q
       SET status = 'processing',
           attempt_count = q.attempt_count + 1,
           locked_at = CURRENT_TIMESTAMP,
           locked_by = p_worker_id,
           dispatched_at = COALESCE(q.dispatched_at, CURRENT_TIMESTAMP)
      FROM candidate c
     WHERE q.id = c.id
    RETURNING q.*
      INTO v_claimed;

    IF NOT FOUND THEN
        RETURN NULL;
    END IF;

    RETURN v_claimed;
END;
$$;


-- ============================================================================
-- 8. RETRY BACKOFF WORKFLOW
-- ============================================================================
-- A failed operation is not immediately retried in a tight loop.
--
-- Backoff:
--   delay = min(base_delay * 2^(attempt_count - 1), max_delay)
--
-- Example with 5-second base and 5-minute cap:
--   attempt 1 -> 5 seconds
--   attempt 2 -> 10 seconds
--   attempt 3 -> 20 seconds
--   ...
--   capped at 5 minutes
--
-- The row remains durable and becomes claimable again at available_at.
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.schedule_retry
(
    p_sync_queue_id UUID,
    p_error TEXT,
    p_base_delay_seconds INTEGER DEFAULT 5,
    p_max_delay_seconds INTEGER DEFAULT 300
)
RETURNS TIMESTAMPTZ
LANGUAGE plpgsql
AS $$
DECLARE
    v_queue offline_sync.sync_queue%ROWTYPE;
    v_delay_seconds BIGINT;
    v_next_attempt INTEGER;
    v_available_at TIMESTAMPTZ;
BEGIN
    IF p_base_delay_seconds < 1
       OR p_max_delay_seconds < p_base_delay_seconds
    THEN
        RAISE EXCEPTION 'Invalid retry backoff parameters';
    END IF;

    SELECT *
      INTO v_queue
      FROM offline_sync.sync_queue
     WHERE id = p_sync_queue_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Sync queue row % does not exist', p_sync_queue_id;
    END IF;

    IF v_queue.status <> 'processing' THEN
        RAISE EXCEPTION
            'Only processing queue rows can be scheduled for retry; current status=%',
            v_queue.status;
    END IF;

    v_next_attempt := GREATEST(v_queue.attempt_count, 1);

    v_delay_seconds :=
        LEAST(
            p_max_delay_seconds::BIGINT,
            p_base_delay_seconds::BIGINT
            * power(2::numeric, LEAST(v_next_attempt - 1, 30))::BIGINT
        );

    v_available_at :=
        CURRENT_TIMESTAMP + make_interval(secs => v_delay_seconds::DOUBLE PRECISION);

    UPDATE offline_sync.sync_queue
       SET status = 'failed',
           available_at = v_available_at,
           locked_at = NULL,
           locked_by = NULL,
           last_error = left(COALESCE(p_error, 'Unknown sync failure'), 4000)
     WHERE id = p_sync_queue_id;

    RETURN v_available_at;
END;
$$;


-- ============================================================================
-- 9. MARK A QUEUED OPERATION AS CONFLICT
-- ============================================================================
-- The actual domain update must be performed by the consuming service in the
-- same transaction as conflict creation. This function only records the
-- conflict and changes queue state.
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.record_conflict
(
    p_sync_queue_id UUID,
    p_client_version BIGINT,
    p_server_version BIGINT,
    p_client_payload JSONB,
    p_server_payload JSONB,
    p_detected_by_device_id UUID DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
    v_queue offline_sync.sync_queue%ROWTYPE;
    v_conflict_id UUID;
BEGIN
    SELECT *
      INTO v_queue
      FROM offline_sync.sync_queue
     WHERE id = p_sync_queue_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Sync queue row % does not exist', p_sync_queue_id;
    END IF;

    IF p_client_version = p_server_version THEN
        RAISE EXCEPTION
            'OFF-05: conflict requires different client and server versions';
    END IF;

    INSERT INTO offline_sync.sync_conflicts
    (
        organization_id,
        sync_queue_id,
        record_type,
        record_id,
        client_version,
        server_version,
        client_payload,
        server_payload,
        detected_by_device_id
    )
    VALUES
    (
        v_queue.organization_id,
        v_queue.id,
        v_queue.record_type,
        v_queue.record_id,
        p_client_version,
        p_server_version,
        p_client_payload,
        p_server_payload,
        p_detected_by_device_id
    )
    RETURNING id
    INTO v_conflict_id;

    UPDATE offline_sync.sync_queue
       SET status = 'conflict',
           completed_at = NULL,
           dispatched_at = COALESCE(dispatched_at, CURRENT_TIMESTAMP)
     WHERE id = p_sync_queue_id;

    RETURN v_conflict_id;
END;
$$;


-- ============================================================================
-- 10. RESOLVE A CONFLICT
-- ============================================================================
-- Human resolution is explicit. No automatic last-write-wins is performed.
-- The caller is responsible for applying resolution_payload to the domain
-- record in the same transaction as this status update.
-- ============================================================================

CREATE OR REPLACE FUNCTION offline_sync.resolve_conflict
(
    p_conflict_id UUID,
    p_resolution TEXT,
    p_resolution_payload JSONB,
    p_resolution_notes TEXT,
    p_resolved_by UUID
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_status TEXT;
BEGIN
    SELECT status
      INTO v_status
      FROM offline_sync.sync_conflicts
     WHERE id = p_conflict_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Sync conflict % does not exist', p_conflict_id;
    END IF;

    IF v_status NOT IN ('open', 'in_review') THEN
        RAISE EXCEPTION
            'Sync conflict % is already terminal: %',
            p_conflict_id,
            v_status;
    END IF;

    IF p_resolution NOT IN
       ('accept_client', 'keep_server', 'merge')
    THEN
        RAISE EXCEPTION 'Invalid conflict resolution: %', p_resolution;
    END IF;

    IF p_resolved_by IS NULL THEN
        RAISE EXCEPTION 'Human resolver is required';
    END IF;

    UPDATE offline_sync.sync_conflicts
       SET status = 'resolved',
           resolution = p_resolution,
           resolution_payload = p_resolution_payload,
           resolution_notes = p_resolution_notes,
           resolved_at = CURRENT_TIMESTAMP,
           resolved_by = p_resolved_by
     WHERE id = p_conflict_id;

    -- The caller must apply the selected resolution to the domain record in
    -- the same transaction before/around this function call. Once that
    -- transaction succeeds, the queue operation is terminal and later
    -- sequence numbers may proceed.
    UPDATE offline_sync.sync_queue q
       SET status = 'completed',
           completed_at = CURRENT_TIMESTAMP,
           locked_at = NULL,
           locked_by = NULL,
           last_error = NULL
      FROM offline_sync.sync_conflicts c
     WHERE c.id = p_conflict_id
       AND q.id = c.sync_queue_id;
END;
$$;


-- ============================================================================
-- 11. TENANT RLS
-- ============================================================================
-- Tenant identity is taken from the authenticated PostgreSQL session context:
--     app.organization_id
--
-- No organization_id supplied by the request is trusted for authorization.
-- ============================================================================

ALTER TABLE offline_sync.syncable_record_versions
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE offline_sync.sync_queue
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE offline_sync.sync_conflicts
    ENABLE ROW LEVEL SECURITY;


CREATE POLICY syncable_record_versions_tenant_isolation
    ON offline_sync.syncable_record_versions
    USING (
        organization_id = app.require_organization_context()
    )
    WITH CHECK (
        organization_id = app.require_organization_context()
    );


CREATE POLICY sync_queue_tenant_isolation
    ON offline_sync.sync_queue
    USING (
        organization_id = app.require_organization_context()
    )
    WITH CHECK (
        organization_id = app.require_organization_context()
    );


CREATE POLICY sync_conflicts_tenant_isolation
    ON offline_sync.sync_conflicts
    USING (
        organization_id = app.require_organization_context()
    )
    WITH CHECK (
        organization_id = app.require_organization_context()
    );


-- ============================================================================
-- 12. MOBILE SQLITE SCHEMA DESIGN GUIDANCE
-- ============================================================================
-- The following is documentation only. It is intentionally not executed.
--
-- Suggested encrypted local SQLite contract:
--
--   CREATE TABLE sync_queue (
--       local_id TEXT PRIMARY KEY,
--       record_type TEXT NOT NULL,
--       record_id TEXT NOT NULL,
--       operation TEXT NOT NULL,
--       base_version INTEGER NOT NULL,
--       payload TEXT NOT NULL,
--       idempotency_key TEXT NOT NULL UNIQUE,
--       sequence_no INTEGER NOT NULL,
--       status TEXT NOT NULL,
--       attempt_count INTEGER NOT NULL DEFAULT 0,
--       available_at TEXT NOT NULL,
--       last_error TEXT,
--       created_at TEXT NOT NULL,
--       updated_at TEXT NOT NULL
--   );
--
--   CREATE TABLE sync_conflicts (
--       id TEXT PRIMARY KEY,
--       record_type TEXT NOT NULL,
--       record_id TEXT NOT NULL,
--       client_version INTEGER NOT NULL,
--       server_version INTEGER NOT NULL,
--       client_payload TEXT NOT NULL,
--       server_payload TEXT NOT NULL,
--       status TEXT NOT NULL,
--       detected_at TEXT NOT NULL,
--       resolution TEXT,
--       resolution_payload TEXT
--   );
--
--   CREATE TABLE sync_metadata (
--       key TEXT PRIMARY KEY,
--       value TEXT NOT NULL
--   );
--
-- Mobile security guidance:
--   1. Encrypt the SQLite database at rest using the mobile team's approved
--      platform/database encryption mechanism.
--   2. Do not store the database encryption key in source code, plain-text
--      configuration, SharedPreferences/UserDefaults, or the SQLite database.
--   3. Android: protect the database key with Android Keystore.
--   4. iOS: protect the database key with Keychain using appropriate device
--      accessibility/protection settings.
--   5. Do not treat a mobile-generated sequence number or version as an
--      authorization decision. Server-side version validation remains
--      authoritative.
--   6. Retry the same operation with the same idempotency_key.
--   7. Do not delete a local queue item until the server acknowledges terminal
--      completion or conflict.
--   8. When a conflict is returned, display both client and server versions
--      and require an explicit human resolution for critical records.


-- ============================================================================
-- 13. COMMENTS FOR IMPLEMENTATION / REVIEW
-- ============================================================================

COMMENT ON SCHEMA offline_sync IS
'DB-018 offline synchronization: durable queue, version tracking, and human-resolvable conflicts.';

COMMENT ON TABLE offline_sync.syncable_record_versions IS
'Authoritative server-side optimistic-concurrency version for registered syncable records.';

COMMENT ON TABLE offline_sync.sync_queue IS
'Durable, ordered, resumable, idempotent offline operation queue.';

COMMENT ON TABLE offline_sync.sync_conflicts IS
'OFF-05 conflict store preserving both client and server versions until human resolution.';

COMMENT ON COLUMN offline_sync.sync_queue.idempotency_key IS
'Stable client-generated key reused for every retry of the same operation.';

COMMENT ON COLUMN offline_sync.sync_queue.sequence_no IS
'Monotonic client/device sequence used to preserve operation ordering.';

COMMENT ON COLUMN offline_sync.sync_conflicts.client_payload IS
'Exact client-side version submitted for the conflicting operation.';

COMMENT ON COLUMN offline_sync.sync_conflicts.server_payload IS
'Server representation observed when the version conflict was detected.';


COMMIT;
